### PR TITLE
Fix spelling error

### PR DESCRIPTION
**Pull request by LennyPenny**

### CODE REVIEW

**Comment by bmwalters** [comment]
Somebody wants his Hacktoberfest T-Shirt...

**Comment by LennyPenny** [comment]
what are you talking about

**Comment by meepen** [comment]
this is absolute shit please close this and ban lennypenny from this repo thanks

**Comment by notcake** [comment]
@meepdarknessmeep please make an issue for that

**Comment by LennyPenny** [comment]
o w n e d

**Comment by SpencerSharkey** [comment]
u guise r funny

**Pull request merged**
